return {}
-- return {
--   {
--     "CopilotC-Nvim/CopilotChat.nvim",
--     dependencies = {
--       { "nvim-lua/plenary.nvim", branch = "master" },
--     },
--     build = "make tiktoken",
--     opts = {
--       model = "claude sonnet 4", -- AI model to use
--       temperature = 0.1, -- Lower = focused, higher = creative
--       window = {
--         layout = "float",
--         width = 80, -- Fixed width in columns
--         height = 20, -- Fixed height in rows
--         border = "rounded", -- 'single', 'double', 'rounded', 'solid'
--         title = "🤖 AI Assistant",
--         zindex = 100, -- Ensure window stays on top
--       },
--       auto_insert_mode = true, -- Enter insert mode when opening
--
--       headers = {
--         user = "👤 You",
--         assistant = "🤖 Copilot",
--         tool = "🔧 Tool",
--       },
--       chat_autocomplete = false,
--       separator = "━━",
--       auto_fold = true, -- Automatically folds non-assistant messages
--     },
--   },
-- }
